DROP FUNCTION IF EXISTS OBTENER_GENERO_PELICULA();

CREATE FUNCTION OBTENER_GENERO_PELICULA()
RETURNS SETOF public.GENERO_PELICULA AS
$BODY$
	SELECT 
		id_genero_pelicula, 
		nombre_genero
	FROM public.GENERO_PELICULA;
$BODY$
LANGUAGE 'sql';
