CREATE OR REPLACE FUNCTION ELIMINA_PERSONA
(
	integer
) RETURNS BOOL AS
$BODY$
DECLARE
	codigo ALIAS FOR $1;
BEGIN
	DELETE FROM public.persona WHERE id_persona = codigo;
	IF FOUND THEN
		RETURN TRUE;
	END IF;
	RETURN FALSE;
END;

$BODY$  LANGUAGE 'plpgsql' VOLATILE;
